objects/Invoice.object
<CustomObject>
    <fields>
        <fullName>VAT_Rate__c</fullName>
        <label>VAT Rate</label>
        <precision>4</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VAT_Rate__c</fullName>
        <label>VAT Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoice_Item__c.object
<CustomObject>
    <fields>
        <fullName>InvoiceId__c</fullName>
        <label>Invoice Id</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Net_Unit_Price__c</fullName>
        <label>Net Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>Invoice_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAT_Rate__c</fullName>
        <label>VAT Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <label>Invoice Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>VAT_Rate__c</fullName>
        <label>VAT Rate</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                    <label>0%</label>
                </value>
                <value>
                    <fullName>0.05</fullName>
                    <label>5%</label>
                </value>
                <value>
                    <fullName>0.27</fullName>
                    <label>27%</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateInvoiceFromOrder.cls
/**  
 * Class to create Invoice from Order
 * @author   Bence Baranyai	<bence.baranyai@evocrm.hu> 
 * @since    2020-10-21
*/


public class CreateInvoiceFromOrder  {
	
	public static Boolean FailedToInsertException = false;

	@AuraEnabled
	public static  String getOrderItems(String orderId){

		Order order = [select OrderNumber, Id, VAT_Rate__c FROM Order Where Id = :orderId];

		List<OrderItem> orderItemList = new List<OrderItem>();
		orderItemList =  [Select Product2.Name, Id, Product2Id, Quantity, UnitPrice, TotalPrice FROM OrderItem where OrderId = :orderId];


		Double VAT = Double.valueOf(order.VAT_Rate__C );
		Invoice__c invoice = new Invoice__c(Name = order.OrderNumber, Order__c = orderId, VAT_Rate__c = VAT);
		insert invoice;

		List<Invoice_Item__c> invoiceItemList = new List<Invoice_Item__c>();


		for(Integer i = 0;i<orderItemList.size();++i){

			//adding values to the necessary fields that are not handled by the InvoiceItem.trigger
			invoiceItemList.add(new Invoice_Item__c(Name = orderItemList.get(i).Product2.Name + ' invoice',
													InvoiceId__c = invoice.Id,
													Net_Unit_Price__c = orderItemList.get(i).UnitPrice,
													Quantity__c = orderItemList.get(i).Quantity,
													Product__c = orderItemList.get(i).Product2Id,
													Order_Product__c = orderItemList.get(i).Id,
													Vat_Rate__c = invoice.VAT_Rate__c													
													));
		}

		//try catch for the front-end feedback
		try{	

			//for test
			if(FailedToInsertException == true){
				throw new CustomException('Failed to insert');
			}
				
			insert invoiceItemList;
			
		}catch(Exception e){
			return 'Something went wrong. The error message is: ' + e.getMessage();
			
		}
		return 'Successfully created invoices.';
		


	}


	

}