objects/Invoice_Item__c.object
<CustomObject>
    <fields>
        <fullName>Gross_Item_Total_Price__c</fullName>
        <label>Gross Item Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Unit_Price__c</fullName>
        <label>Gross Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item_Total_VAT_Price__c</fullName>
        <label>Item Total VAT Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Item_Total_Price__c</fullName>
        <label>Net Item Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Unit_Price__c</fullName>
        <label>Net Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VAT_Rate__c</fullName>
        <label>VAT Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <label>Invoice Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UpdateInvoiceItemFields.cls
public class UpdateInvoiceItemFields  {

	 public static void updateItemTotalPriceFields(List<Invoice_Item__c> triggerList) {
		
		for(Invoice_Item__c thisItem : triggerList) {
			thisItem.Net_Item_Total_Price__c = thisItem.Quantity__c * thisItem.Net_Unit_Price__c;
			thisItem.Gross_Unit_Price__c = thisItem.Net_Unit_Price__c * (1 + thisItem.VAT_Rate__c);
			thisItem.Gross_Item_Total_Price__c = thisItem.Gross_Unit_Price__c * thisItem.Quantity__c;
			thisItem.Item_Total_VAT_Price__c = thisItem.Gross_Item_Total_Price__c - thisItem.Net_Item_Total_Price__c;
		}
	 }
}